name: update list
on:
  push:
  schedule:
    - cron: '0 14 * * FRI'
jobs:
  modify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: EndBug/add-and-commit@v7
      with:
          remove: '*.m3u --force'     
    - name: cd to root
      run: cd /
    - name: wget
      run: wget https://raw.githubusercontent.com/wuwentao/bj-unicom-iptv/master/bj-unicom-iptv.m3u -O indoor-bj-unicom-iptv.m3u
    - name: modify indoor
      run: find -name 'indoor-bj-unicom-iptv.m3u' | xargs perl -pi -e 's|rtp://|http://10.10.10.1:8680/udp/|g'
    - uses: EndBug/add-and-commit@v7
      with:
          message: 'Add new file'
          add: '*.m3u --force'
          push: 'origin ${{ github.event.inputs.branch }} --force'
